### PR TITLE
fix: config express app to use built-in Node query parser which handles large benchmarkId arrays instead of `qs`

### LINKED ISSUE #2034: metrics endpoints reject queries with > 20 `benchmarkId` values after qs upgrade
## Context

In release 1.6.1 (a dependency-only update), API requests to `/api/collections/{collectionId}/metrics/summary` (and the other `array + explode` query parameter endpoints) began failing with:

```
{"error":"request/query/benchmarkId/0 must be string"}
```

whenever the request carried more than 20 repeated `benchmarkId=…` query parameters. The Vue export-checklist UI builds this URL with **every** STIG in the collection by default, so any installation with > 20 STIGs sees the error as soon as that dialog opens.

### Root cause (verified end-to-end)

1. `qs` 6.13.0 → 6.14.1 (pulled in transitively by `express` ^4.21.2) extended its `arrayLimit` (default `20`) to also apply to repeated bare keys (`a=1&a=2&...`), which the changelog notes as *"ensure arrayLimit applies to `[]` notation as well."*
2. Above the limit, `qs.parse()` returns a numeric-keyed **object** (`{ '0': 'A', '1': 'B', … }`) instead of a string array.
3. `express-openapi-validator`'s `explodeJsonArrayAndMutateRequest` ([req.parameter.mutator.js:284-294](api/source/node_modules/express-openapi-validator/dist/middlewares/parsers/req.parameter.mutator.js#L284-L294)) sees a non-array value for an `array + explode` parameter and wraps it: `[{0:'A', 1:'B', …}]`.
4. AJV validates index 0, finds an object instead of a string, and raises `request/query/benchmarkId/0 must be string` — exactly the customer's report.

Reproduced locally end-to-end (with the project's exact installed dependencies and OpenAPI spec): 20 repeated keys → 200 OK, 21 keys → 400 with the exact error string. Also reproduced the qs change in isolation by parsing the same string with `qs@6.13.0` (returns an array) versus `qs@6.14.1` (returns an object). This is **not** a customer proxy issue.

### Affected endpoints

Every endpoint using `BenchmarkIdArrayQuery` or `AssetIdArrayQuery` (any `type: array` + `style: form, explode: true` query param). That includes the metrics summary/detail family on collections and the meta metrics endpoints. The failure threshold is the same 20-element ceiling for any of them.

### PR DESCRIPTION
**Pull request by cd-rite**
Restores array semantics for repeated query params after qs ≥ 6.14
Resolves: #2034 

## Summary

- Install a custom Express query parser that raises qs's `arrayLimit` so that endpoints accepting `array + explode` query parameters (e.g. `benchmarkId`, `assetId`) keep their array semantics for any realistic count.
- Add a regression test that exercises `GET /collections/{id}/metrics/summary` with > 20 `benchmarkId` values.

## Issue

Starting in 1.6.1 (a dependency-only release), requests to the metrics endpoints fail with HTTP 400 once the caller passes more than 20 repeated `benchmarkId` query parameters:

The export-checklist dialog builds this URL with **every** STIG in the collection by default, so any installation with more than 20 STIGs hits the error as soon as that dialog opens. Endpoints accepting `AssetIdArrayQuery` are affected by the same ceiling.

## Fix

`app.set('query parser', fn)` is Express's documented mechanism for swapping in a custom parser ([api docs](https://expressjs.com/en/api.html)) — the function receives the raw query string and returns the parsed object. Express forwards the function verbatim to its internal `query()` middleware, so a thin wrapper around `qs.parse` with `arrayLimit` raised is sufficient.

```js
app.set('query parser', str => qs.parse(str, { arrayLimit: 5000, allowPrototypes: true }))
```

- arrayLimit: 5000 restores effectively-unbounded array behaviour while keeping a defensive ceiling. The practical bound is the URL/header byte limit.
- allowPrototypes: true matches what Express's built-in 'extended' parser was doing for back-compat, so the override doesn't introduce an unrelated behaviour change.
- qs is already on disk as a transitive dep of express; no new top-level dependency.

The call must run before any app.use() on the app: Express's lazyrouter() binds the query parser to the router on the first middleware registration and ignores later changes. configureMulter is the first item in the bootstrap list, so the app.set is hoisted to the top of configureMiddleware (above the middleware loop) with a comment explaining the ordering requirement.

### CODE REVIEW

File: api/source/bootstrap/middlewares.js [hunk 1]
```diff
@@ -14,6 +15,13 @@ const logger = require('../utils/logger')
 
 function configureMiddleware(app) {
 
+    // Must run before any app.use() call: Express's lazyrouter binds the query
+    // parser at the moment the first middleware is registered and ignores
+    // later changes. qs >=6.14 enforces arrayLimit on repeated bare keys, which
+    // would otherwise corrupt type:array+explode params (e.g., benchmarkId,
+    // assetId) once they exceed 20 values.
+    app.set('query parser', str => qs.parse(str, { arrayLimit: 5000, allowPrototypes: true }))
+
```
Comment (csmig) [inline api/source/bootstrap/middlewares.js]: I have pushed a commit:

```js
app.set('query parser','simple')
```
which uses Node's built-in query parser. When we do this, the large benchmarkId array test passes along with all other tests. Confirmed that an array(100) also passes.

This pattern removes a direct dependency on `qs`. Our OAS definition does not contain complicated, nested query params requiring parsing by `qs`.

**Review by csmig — COMMENTED** [review]
I am suggesting a simplified solution
